import { join } from "node:path";
import { writeFile } from "fs-extra";

/**
 * Generate a .env file with the provided configuration values
 */
export async function generateEnvFile(
	targetDir: string,
	values: Record<string, string>,
): Promise<void> {
	const lines = [
		"# Generated by ClaudeKit CLI setup wizard",
		"# See .env.example for all available options",
		"",
	];

	for (const [key, value] of Object.entries(values)) {
		if (value) {
			lines.push(`${key}=${value}`);
		}
	}

	const envPath = join(targetDir, ".env");
	// Set restrictive permissions (owner read/write only) for security
	await writeFile(envPath, `${lines.join("\n")}\n`, { mode: 0o600 });
}
