import { describe, expect, test } from "bun:test";
import {
	getDisclaimerMarker,
	isOwnComment,
} from "../../../commands/watch/phases/comment-poller.js";

describe("isOwnComment", () => {
	test("detects own comment by HTML marker", () => {
		expect(
			isOwnComment(
				"<!-- ck-watch-bot -->\n\n> *This response was generated by AI*\n\nSome response",
			),
		).toBe(true);
	});

	test("detects marker anywhere in body", () => {
		expect(isOwnComment("Some text <!-- ck-watch-bot --> more text")).toBe(true);
	});

	test("does not match normal comments", () => {
		expect(isOwnComment("This is a user comment")).toBe(false);
	});

	test("does not match partial marker", () => {
		expect(isOwnComment("<!-- ck-watch -->")).toBe(false);
	});
});

describe("getDisclaimerMarker", () => {
	test("returns the HTML comment marker", () => {
		expect(getDisclaimerMarker()).toBe("<!-- ck-watch-bot -->");
	});
});
