import { describe, expect, test } from "bun:test";
import {
	formatResponse,
	scanForCredentials,
	stripMentions,
} from "../../../commands/watch/phases/response-poster.js";

describe("scanForCredentials", () => {
	test("detects RSA private key", () => {
		expect(scanForCredentials("-----BEGIN RSA PRIVATE KEY-----")).toBe(true);
	});

	test("detects EC private key", () => {
		expect(scanForCredentials("-----BEGIN EC PRIVATE KEY-----")).toBe(true);
	});

	test("detects GitHub PAT (ghp_)", () => {
		expect(scanForCredentials("token: ghp_abcdefghijklmnopqrstuvwxyz1234567890")).toBe(true);
	});

	test("detects GitHub fine-grained PAT", () => {
		const pat = `github_pat_${"a".repeat(82)}`;
		expect(scanForCredentials(pat)).toBe(true);
	});

	test("detects Anthropic API key", () => {
		expect(scanForCredentials("sk-ant-api03-abc123")).toBe(true);
	});

	test("detects OpenAI API key", () => {
		expect(scanForCredentials(`sk-${"a".repeat(48)}`)).toBe(true);
	});

	test("detects AWS access key", () => {
		expect(scanForCredentials("AKIAIOSFODNN7EXAMPLE")).toBe(true);
	});

	test("detects password assignment", () => {
		expect(scanForCredentials('password = "mysecret123"')).toBe(true);
	});

	test("detects Bearer token", () => {
		expect(scanForCredentials("Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9")).toBe(
			true,
		);
	});

	test("passes clean content", () => {
		expect(scanForCredentials("This is a normal response about implementing dark mode")).toBe(
			false,
		);
	});

	test("passes code snippets without secrets", () => {
		expect(scanForCredentials("const API_URL = 'https://api.example.com'")).toBe(false);
	});
});

describe("stripMentions", () => {
	test("escapes @username to backtick format", () => {
		expect(stripMentions("Hey @user check this")).toBe("Hey `@user` check this");
	});

	test("escapes multiple mentions", () => {
		expect(stripMentions("cc @alice @bob")).toBe("cc `@alice` `@bob`");
	});

	test("preserves email addresses", () => {
		expect(stripMentions("email: user@example.com")).toBe("email: user@example.com");
	});

	test("handles @mention at start of line", () => {
		expect(stripMentions("@user please review")).toBe("`@user` please review");
	});
});

describe("formatResponse", () => {
	test("includes AI disclaimer", () => {
		const result = formatResponse("Hello", true);
		expect(result).toContain("<!-- ck-watch-bot -->");
		expect(result).toContain("generated by AI");
	});

	test("includes branding when enabled", () => {
		const result = formatResponse("Hello", true);
		expect(result).toContain("ClaudeKit");
	});

	test("omits branding when disabled", () => {
		const result = formatResponse("Hello", false);
		expect(result).not.toContain("Powered by");
	});

	test("always includes disclaimer even without branding", () => {
		const result = formatResponse("Hello", false);
		expect(result).toContain("<!-- ck-watch-bot -->");
		expect(result).toContain("generated by AI");
	});

	test("truncates at 60000 chars", () => {
		const long = "x".repeat(70000);
		const result = formatResponse(long, true);
		expect(result.length).toBeLessThanOrEqual(65000);
		expect(result).toContain("[Response truncated]");
	});

	test("strips @mentions in content", () => {
		const result = formatResponse("Hey @user check this out", true);
		expect(result).toContain("`@user`");
	});
});
