/**
 * Response poster — posts sanitized responses to GitHub issues via gh CLI
 * Scans for credentials, strips @mentions, adds AI disclaimer on every post
 * Uses stdin for body content (never command args) to prevent shell injection
 */

import { spawn } from "node:child_process";
import { logger } from "@/shared/logger.js";
import { getDisclaimerMarker } from "./comment-poller.js";

// Credential patterns that BLOCK posting entirely (not just redact)
const CREDENTIAL_PATTERNS = [
	/-----BEGIN\s+(RSA|DSA|EC|OPENSSH)\s+PRIVATE\s+KEY-----/,
	/ghp_[a-zA-Z0-9]{36}/,
	/github_pat_[a-zA-Z0-9_]{82}/,
	/sk-ant-[a-zA-Z0-9-]+/,
	/sk-[a-zA-Z0-9]{48,}/,
	/AKIA[A-Z0-9]{16}/,
	/password\s*[=:]\s*['"][^'"]+['"]/i,
	/secret\s*[=:]\s*['"][^'"]+['"]/i,
	/Bearer\s+[a-zA-Z0-9._-]{20,}/,
];

/**
 * Post a raw response to a GitHub issue without mention-stripping
 * Used for approval-request comments that intentionally mention the owner
 * Returns false if posting was blocked (credentials detected) or failed
 */
export async function postRawResponse(
	owner: string,
	repo: string,
	issueNumber: number,
	content: string,
	showBranding: boolean,
	dryRun: boolean,
): Promise<boolean> {
	if (scanForCredentials(content)) {
		logger.warning(`Response for #${issueNumber} blocked: credential pattern detected`);
		return false;
	}

	const disclaimer = `${getDisclaimerMarker()}\n\n> *This response was generated by AI and may contain inaccuracies. Please verify before acting on it.*\n\n`;
	const branding = showBranding ? "\n\n---\n*Powered by [ClaudeKit](https://claudekit.cc)*" : "";
	const maxLen = 60_000 - disclaimer.length - branding.length;
	let formatted = content;
	if (formatted.length > maxLen) {
		formatted = `${formatted.slice(0, maxLen)}\n\n*[Response truncated]*`;
	}
	const body = disclaimer + formatted + branding;

	if (dryRun) {
		logger.info(`[dry-run] Would post raw to #${issueNumber} (${body.length} chars)`);
		return true;
	}

	try {
		await postViaGh(owner, repo, issueNumber, body);
		return true;
	} catch (error) {
		logger.warning(`First post attempt failed for #${issueNumber}, retrying...`);
		try {
			await postViaGh(owner, repo, issueNumber, body);
			return true;
		} catch (retryError) {
			logger.error(`Failed to post to #${issueNumber}: ${(retryError as Error).message}`);
			return false;
		}
	}
}

/**
 * Post a formatted response to a GitHub issue
 * Returns false if posting was blocked (credentials detected) or failed
 */
export async function postResponse(
	owner: string,
	repo: string,
	issueNumber: number,
	content: string,
	showBranding: boolean,
	dryRun: boolean,
): Promise<boolean> {
	// 1. Scan for credentials — block entirely if found
	if (scanForCredentials(content)) {
		logger.warning(`Response for #${issueNumber} blocked: credential pattern detected`);
		return false;
	}

	// 2. Format response with disclaimer + branding + truncation
	const formatted = formatResponse(content, showBranding);

	// 3. Dry-run: log but don't post
	if (dryRun) {
		logger.info(`[dry-run] Would post to #${issueNumber} (${formatted.length} chars)`);
		logger.verbose("Response preview:", { body: formatted.slice(0, 300) });
		return true;
	}

	// 4. Post via gh issue comment with stdin
	try {
		await postViaGh(owner, repo, issueNumber, formatted);
		return true;
	} catch (error) {
		// Retry once on transient failure
		logger.warning(`First post attempt failed for #${issueNumber}, retrying...`);
		try {
			await postViaGh(owner, repo, issueNumber, formatted);
			return true;
		} catch (retryError) {
			logger.error(`Failed to post to #${issueNumber}: ${(retryError as Error).message}`);
			return false;
		}
	}
}

/**
 * Scan content for credential patterns
 * Returns true if ANY pattern matches (post should be blocked)
 */
export function scanForCredentials(content: string): boolean {
	return CREDENTIAL_PATTERNS.some((p) => p.test(content));
}

/**
 * Strip @username mentions (but not email addresses) to prevent unwanted notifications
 */
export function stripMentions(content: string): string {
	return content.replace(/(?<!\S)@([a-zA-Z0-9-]+)/g, "`@$1`");
}

/**
 * Format the response with disclaimer, mention-stripping, branding, and truncation
 */
export function formatResponse(content: string, showBranding: boolean): string {
	let formatted = stripMentions(content);

	// Non-configurable AI disclaimer (hidden HTML comment for own-comment detection)
	const disclaimer = `${getDisclaimerMarker()}\n\n> *This response was generated by AI and may contain inaccuracies. Please verify before acting on it.*\n\n`;

	// Optional CK branding (showBranding controls this; disclaimer is always present)
	const branding = showBranding ? "\n\n---\n*Powered by [ClaudeKit](https://claudekit.cc)*" : "";

	// Truncate to 60,000 chars (GitHub limit ~65,535)
	const maxLen = 60_000 - disclaimer.length - branding.length;
	if (formatted.length > maxLen) {
		formatted = `${formatted.slice(0, maxLen)}\n\n*[Response truncated]*`;
	}

	return disclaimer + formatted + branding;
}

/**
 * Post body via gh issue comment using stdin (NOT --body arg)
 */
async function postViaGh(
	owner: string,
	repo: string,
	issueNumber: number,
	body: string,
): Promise<void> {
	return new Promise((resolve, reject) => {
		const args = [
			"issue",
			"comment",
			String(issueNumber),
			"--repo",
			`${owner}/${repo}`,
			"--body-file",
			"-", // Read body from stdin
		];

		const child = spawn("gh", args, { stdio: ["pipe", "pipe", "pipe"] });
		const stderrChunks: Buffer[] = [];

		child.stderr.on("data", (chunk: Buffer) => stderrChunks.push(chunk));

		// Pass body via stdin (never as command arg)
		child.stdin.write(body);
		child.stdin.end();

		child.on("error", (err) => reject(new Error(`Failed to spawn gh: ${err.message}`)));
		child.on("close", (code) => {
			if (code !== 0) {
				const stderr = Buffer.concat(stderrChunks).toString("utf-8");
				reject(new Error(`gh exited with code ${code}: ${stderr}`));
				return;
			}
			resolve();
		});
	});
}
