import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateEnvFile } from "../../src/domains/config/config-generator.js";

describe("config-generator", () => {
	let tempDir: string;

	beforeEach(async () => {
		tempDir = join(tmpdir(), `ck-test-${Date.now()}`);
		await mkdir(tempDir, { recursive: true });
	});

	afterEach(async () => {
		await rm(tempDir, { recursive: true, force: true });
	});

	test("should generate .env file with values", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123",
			DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/123/abc",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("GEMINI_API_KEY=AIzaSyTest123");
		expect(content).toContain("DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/123/abc");
	});

	test("should skip empty values", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123",
			EMPTY_KEY: "",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("GEMINI_API_KEY");
		expect(content).not.toContain("EMPTY_KEY");
	});

	test("should include header comments", async () => {
		await generateEnvFile(tempDir, { KEY: "value" });

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("# Generated by ClaudeKit CLI");
	});
});
