import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { CodexCapabilities } from "../codex-capabilities.js";
import { CODEX_CAPABILITY_TABLE } from "../codex-capabilities.js";
import { buildWrapperScript, generateCodexHookWrappers } from "../codex-hook-wrapper.js";

const testDir = join(tmpdir(), "ck-codex-hook-wrapper-test");
const caps: CodexCapabilities = CODEX_CAPABILITY_TABLE[0];

beforeAll(() => {
	mkdirSync(testDir, { recursive: true });
});

afterAll(() => {
	rmSync(testDir, { recursive: true, force: true });
});

describe("buildWrapperScript", () => {
	it("includes the original hook path in the script", () => {
		const script = buildWrapperScript("/home/user/.claude/hooks/session-init.cjs", caps);
		expect(script).toContain("/home/user/.claude/hooks/session-init.cjs");
	});

	it("generates a valid CommonJS shebang", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script.startsWith("#!/usr/bin/env node")).toBe(true);
	});

	it("contains the AUTO-GENERATED marker", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("AUTO-GENERATED by claudekit");
	});

	it("encodes strip rules for PreToolUse (additionalContext)", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// PreToolUse does not support additionalContext → must be in STRIP_RULES
		expect(script).toContain("PreToolUse");
		expect(script).toContain("additionalContext");
	});

	it("does not strip additionalContext for PostToolUse (it is supported)", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// PostToolUse supports additionalContext so should NOT be in STRIP_RULES
		// The STRIP_RULES object only contains events where fields need stripping
		const stripRulesMatch = script.match(/const STRIP_RULES = (\{.*?\});/s);
		if (stripRulesMatch) {
			const stripRules = JSON.parse(stripRulesMatch[1]);
			// PostToolUse should not be in strip rules (it supports additionalContext)
			expect(stripRules.PostToolUse).toBeUndefined();
		}
	});

	it("uses spawnSync to invoke the original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("spawnSync");
	});

	it("reads stdin and passes it to original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("process.stdin");
	});

	it("forwards stderr from original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("process.stderr.write");
	});

	it("parses stdout as JSON and sanitizes it", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("JSON.parse");
		expect(script).toContain("JSON.stringify");
	});

	it("passes through non-JSON output unchanged", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// Script should handle the non-JSON case gracefully
		expect(script).toContain("Not valid JSON");
	});
});

describe("buildWrapperScript — M4 timeout", () => {
	it("M4 — embeds default 30000ms timeout when no hookTimeoutMs provided", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("HOOK_TIMEOUT_MS = 30000");
	});

	it("M4 — embeds custom timeout when hookTimeoutMs provided", () => {
		const script = buildWrapperScript("/hook.cjs", caps, 60000);
		expect(script).toContain("HOOK_TIMEOUT_MS = 60000");
		expect(script).not.toContain("HOOK_TIMEOUT_MS = 30000");
	});

	it("M4 — wrapper uses HOOK_TIMEOUT_MS in spawnSync call", () => {
		const script = buildWrapperScript("/hook.cjs", caps, 45000);
		// Should reference HOOK_TIMEOUT_MS (not hardcoded 30000) in spawnSync options
		expect(script).toContain("timeout: HOOK_TIMEOUT_MS");
	});
});

describe("buildWrapperScript — M5 signal exit", () => {
	it("M5 — uses ?? 1 (not || 0) for exit code fallback", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// Should use nullish coalescing fallback of 1, not short-circuit or 0
		expect(script).toContain("result.status ?? 1");
		expect(script).not.toContain("result.status || 0");
	});
});

describe("generateCodexHookWrappers", () => {
	it("generates wrapper files in target directory", () => {
		const wrapperDir = join(testDir, "wrapper-output");
		const originals = [join(testDir, "session-init.cjs"), join(testDir, "privacy-block.cjs")];

		const results = generateCodexHookWrappers(originals, wrapperDir, caps);

		expect(results).toHaveLength(2);
		for (const r of results) {
			expect(r.success).toBe(true);
			expect(existsSync(r.wrapperPath)).toBe(true);
		}
	});

	it("wrapper file preserves original filename", () => {
		const wrapperDir = join(testDir, "wrapper-names");
		const results = generateCodexHookWrappers(
			["/home/user/.claude/hooks/my-hook.cjs"],
			wrapperDir,
			caps,
		);
		expect(results[0].wrapperPath).toContain("my-hook.cjs");
	});

	it("creates wrapper directory if it does not exist", () => {
		const wrapperDir = join(testDir, "new-wrapper-dir");
		expect(existsSync(wrapperDir)).toBe(false);

		generateCodexHookWrappers(["/original.cjs"], wrapperDir, caps);
		expect(existsSync(wrapperDir)).toBe(true);
	});

	it("returns empty array for empty input", () => {
		const results = generateCodexHookWrappers([], join(testDir, "empty"), caps);
		expect(results).toHaveLength(0);
	});

	it("wrapper content contains reference to original path", () => {
		const wrapperDir = join(testDir, "wrapper-content");
		const originalPath = "/home/user/.claude/hooks/session-init.cjs";

		const results = generateCodexHookWrappers([originalPath], wrapperDir, caps);
		expect(results[0].success).toBe(true);

		const content = readFileSync(results[0].wrapperPath, "utf8");
		expect(content).toContain(originalPath);
	});
});
