/**
 * Phase 2 — Windows wrapper generation tests.
 *
 * Verifies that on win32:
 * - Generated wrapper does NOT start with shebang
 * - First line is a // comment header
 * - Windows path with backslashes is correctly escaped in ORIGINAL_HOOK
 */
import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { CODEX_CAPABILITY_TABLE } from "../codex-capabilities.js";
import type { CodexCapabilities } from "../codex-capabilities.js";
import { buildWrapperScript } from "../codex-hook-wrapper.js";

const caps: CodexCapabilities = CODEX_CAPABILITY_TABLE[0];

describe("buildWrapperScript — Windows paths", () => {
	let originalPlatform: NodeJS.Platform;

	beforeEach(() => {
		originalPlatform = process.platform;
		Object.defineProperty(process, "platform", { value: "win32", configurable: true });
	});

	afterEach(() => {
		Object.defineProperty(process, "platform", {
			value: originalPlatform,
			configurable: true,
		});
	});

	it("win32: generated wrapper does NOT start with shebang line", () => {
		const script = buildWrapperScript("C:\\Users\\kai\\.claude\\hooks\\test.cjs", caps);
		expect(script.startsWith("#!/usr/bin/env node")).toBe(false);
		expect(script).not.toMatch(/^#!\/usr\/bin\/env node/);
	});

	it("win32: first line is a // comment header", () => {
		const script = buildWrapperScript("C:\\Users\\kai\\.claude\\hooks\\test.cjs", caps);
		const firstLine = script.split("\n")[0];
		expect(firstLine.trimStart().startsWith("//")).toBe(true);
	});

	it("win32: ORIGINAL_HOOK constant correctly escapes backslashes", () => {
		const winPath = "C:\\Users\\kai\\.claude\\hooks\\test.cjs";
		const script = buildWrapperScript(winPath, caps);

		// JSON.stringify("C:\\Users\\...") → "C:\\\\Users\\\\..." (double-escaped)
		// Embedded in script as: const ORIGINAL_HOOK = "C:\\Users\\kai\\...";
		// The script content should contain the JSON-escaped form of the Windows path
		const expectedEscaped = JSON.stringify(winPath);
		expect(script).toContain(expectedEscaped);

		// Should NOT contain unescaped \U, \k, etc. (invalid JS escape sequences)
		expect(script).not.toMatch(/ORIGINAL_HOOK = "C:\\[^\\]/);
	});

	it("win32: snapshot of generated wrapper for Windows path", () => {
		const winPath = "C:\\Users\\kai\\.claude\\hooks\\scout-block.cjs";
		const script = buildWrapperScript(winPath, caps);

		// Structural snapshot assertions
		expect(script).toContain("AUTO-GENERATED by claudekit");
		expect(script).toContain("SCRUB_RULES");
		expect(script).toContain("spawnSync");
		expect(script).toContain("ORIGINAL_HOOK");
		// Must NOT have shebang
		expect(script.startsWith("#!")).toBe(false);
		// First non-empty line must be a comment
		const lines = script.split("\n");
		const firstContentLine = lines.find((l) => l.trim().length > 0) ?? "";
		expect(firstContentLine.trimStart().startsWith("//")).toBe(true);
	});

	it("POSIX: wrapper still has no shebang after Phase 2 change (comment header instead)", () => {
		Object.defineProperty(process, "platform", { value: "darwin", configurable: true });
		const script = buildWrapperScript("/home/user/.claude/hooks/test.cjs", caps);
		// After Phase 2: shebang removed on ALL platforms — wrapper always invoked via `node`
		expect(script.startsWith("#!/usr/bin/env node")).toBe(false);
		const firstLine = script.split("\n")[0];
		expect(firstLine.trimStart().startsWith("//")).toBe(true);
	});
});
